### ISSUE TITLE
[BUG] 第五點的指令錯誤

### ISSUE THREAD

**Issue by chang861224** [josix/CPLab#10]
![Screenshot from 2020-09-15 09-50-53](https://user-images.githubusercontent.com/29120309/93155594-0b1f0400-f739-11ea-96ba-f41d222947f7.png)
重新命名的資料夾名稱是`jqk`

**Comment by josix** [comment]
Issue fixed @[90f1d21](https://github.com/josix/CPLab/commit/90f1d215d71f3d6091f0e067de30b8d91f8836c7)
